version: '2'
services:
  matchbox:
    image: quay.io/coreos/matchbox:v0.7.0
    ports:
      - 8080:8080
      - 8081:8081
    command:
      - -address=0.0.0.0:8080
      - -rpc-address=0.0.0.0:8081
      - -log-level=debug
    volumes:
      - ./certs:/etc/matchbox/:Z,ro
      - ./assets:/var/lib/matchbox/assets/:Z,ro
      - ./groups:/var/lib/matchbox/groups/:Z
      - ./ignition:/var/lib/matchbox/ignition/:Z
      - ./profiles:/var/lib/matchbox/profiles/:Z
  # Move netboot to UniFi config
  #   see: https://typhoon.psdn.io/topics/hardware/#ubiquiti
